### ISSUE TITLE
cerbere crashes at logout

### ISSUE THREAD

**Issue by decathorpe** [elementary/cerbere#33] opened 2019-07-30 20:08 UTC
I have only seen this happen on 2.5.0 and not earlier releases, so I'm assuming this has something to do with the new shutdown logic:

```
Program terminated with signal SIGSEGV, Segmentation fault.
Thread 1:
#0 (...) in g_application_release () from /lib64/libgio-2.0.so.0
#1 <signal handler called>
#2 _cerbere_app_handle_sighup_sighandler_t (signal=1) at Cerbere.c:265
#3 <signal handler called>
#4 in __GI__poll (foo bar)
#5 in ?? () from /lib64/libglib-2.0.so.0
#6 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#7 in g_application_run () from /lib64/libglib-2.0.so.0
#8 in cerbere_app_main () at ../src/Cerbere.vala:102
#9 in __libc_start_main ()
#10 in _start () at ../src/Cerbere.vala:100
```

**Comment by decathorpe** [comment] 2019-07-30 20:13
fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1734526

**Comment by vjr** [comment] 2019-07-31 04:48
Possibly multiple calls to `release ()` being triggered where there is only one call to `hold ()` ?

**Comment by jmc-88** [comment] 2019-08-05 16:27
Could be. The documentation doesn't report clearly what will happen on mismatched calls to `release()` and I haven't seen the same task processing multiple shutdown requests (e.g. both `SessionManager` and `SIGTERM`) before closing.

It should be easy to fix though.

**Comment by jmc-88** [comment] 2019-08-07 21:39
Opened https://github.com/elementary/cerbere/pull/34 for a possible fix.
@decathorpe are you able to test if this fixes the issue for you? I can't reproduce locally.

**Comment by decathorpe** [comment] 2019-08-29 20:06
FTR, the linked PR doesn't fix the crash for me.

**Comment by decathorpe** [comment] 2019-09-04 13:28
I'm going to revert the commit that introduces this crash in fedora until it's fixed upstream. I already got over 100 crash reports for cerbere on fedora 30 alone.

**Comment by Blast-City** [comment] 2019-11-15 02:25
I also get this segfaults on reboot and on power-off. It's always the same "error 4 in libgio-2.0.so.0.5600.4"

**Comment by Blast-City** [comment] 2020-03-05 21:53
Last update seems to have fixed this issue. can anyone else confirm?

**Comment by jmc-88** [comment] 2020-03-06 00:09
Well, I bet. I think the last update removed Cerbere:

```
$ pgrep -l cerbere
# zilch
```

**Comment by Blast-City** [comment] 2020-03-06 16:46
> Well, I bet. I think the last update removed Cerbere:
> 
> ```
> $ pgrep -l cerbere
> # zilch
> ```

Haha. I saw a cerbere update and only checked for the segfault error.
My bad. Sorry.

**Comment by danirabbit** [comment] 2020-03-06 16:58
As of the latest updates to elementary OS, Cerbere serves no function. It is safe to remove.

I'm inclined to close this issue since there is no planned future development of Cerbere.

**Closed as completed by danirabbit** 2020-03-06 16:58 UTC
