### ISSUE TITLE
Who watches the watchdog?

### ISSUE THREAD

**Issue by jmc-88** [elementary/cerbere#30] opened 2019-07-01 09:22 UTC
Currently, Cerbere is spawned with the user session by means of `/etc/xdg/autostart/io.elementary.cerbere.desktop`. This file has [`X-Gnome-Autorestart=false`](https://github.com/elementary/cerbere/blob/23d15fdeca66b6a05f6dea3588897ef8bd5e93a7/data/io.elementary.cerbere.desktop.in#L12), so if it terminates (normally or abnormally), it's never restarted for the active session. I thought this was on purpose to avoid restart loops on crashes, but then the AppCenter configuration file has `X-Gnome-Autorestart=true` (?).

This raises a question about the overall value of Cerbere: if it goes down, it never comes back to fulfill its duty. As it's currently only configured to watch over WingPanel and Plank, why not just get rid of it and outsource the task of autorestarting jobs to either gnome-session or systemd user units?

Since the only added feature on top of gnome-session seems to be to give up restarts after too many failures, what could be used instead is systemd units with [`Restart=watchdog`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=) and appropriate rate limiting with [`StartLimitIntervalSec` / `StartLimitBurst`](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=).

**Comment by codygarver** [comment] 2019-07-01 13:35
This would be alleviated by and is basically a duplicate of elementary/os#208

**Closed as completed by codygarver** 2019-07-01 13:35 UTC
